# Generated by Django 4.2.5 on 2023-09-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='vision',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='task',
            name='memo',
            field=models.CharField(blank=True, default='', max_length=800),
        ),
    ]
