# Generated by Django 4.2.5 on 2023-09-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_alter_folder_vision_alter_task_memo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='position',
            field=models.CharField(choices=[('new_graduate', 'Position New Graduate'), ('direct_supervisor', 'Position Direct Supervisor'), ('manager', 'Position Manager')], default='new_graduate', max_length=20, unique=True),
        ),
    ]
